CITIES = {
    "São José dos Campos": "urban",
    "Taubaté": "urban",
    "Guaratinguetá": "urban",
    "Pindamonhangaba": "urban",
    "Jacareí": "urban",
    "Caçapava": "urban",
    "Lorena": "urban",
    "Cruzeiro": "urban",
    "Campos do Jordão": "mountain",
    "Cunha": "mountain",
    "São Bento do Sapucaí": "mountain",
    "Monteiro Lobato": "mountain",
    "São Luiz do Paraitinga": "mountain",
    "Ubatuba": "coastal",
    "Caraguatatuba": "coastal",
    "São Sebastião": "coastal",
    "Ilhabela": "coastal",
}
